### PR TITLE
Move service-like resources to services folder

### PR DESCRIPTION
**Pull request by vikaspotluri123**
This is going to be a pretty large PR, since there's a decent number of moving parts. It is very much WIP.

The purpose for this PR is to create a place for abstract things to happen. The long term goal for implementing this change is having task queues to batch changes. The first use-case for this is analytics / the actions table. As we would like to know how many users, courses, categories and grades are created or deleted in a day, the actions task queue will store changes to be committed to the actions table, and will commit those changes at a constant interval. This means the granularity of our measurements will not be individual. That is, a row in the actions table does not represent a single action, rather it represents the actions that occured in {interval}. The cron service will interface with the actions service to commit changes in this interval. The current interval will be 5 minutes.

The actions table will be compressed / pruned nightly. 
>  _We will store 5-minute intervals for 1 day, 1-day intervals for 1 week, 1-week for 1 month, and 1-month intervals for a year._

   - I'm not so sure this is necessary, as the statistics data should take care of this 🤔 This detail is not super important at the moment, as we can adjust the behavior as needed.

### CODE REVIEW

**Comment by vikaspotluri123** [comment]
Added events for analytics, I'll add statistics / compression in a separate PR

I'm curious what other data we should collect, feel free to mark any suggestions!

Currently:
- User deleted
- Course deleted
- Category expanded
- Category deleted
- Grade deleted

**Comment by vikaspotluri123** [comment]
e

**Comment by joshcosta** [comment]
User logins are another thing we can collect

**Comment by vikaspotluri123** [comment]
Gotta rebase against deps and then I'll merge 🚀

**Pull request merged**
